### ISSUE TITLE
Last.fm Integration

### ISSUE THREAD

**Issue by ghost** [justdotJS/SimplePresence#1]
## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!
- [x] Feature Request
- [ ] Bug Report

## Description
Last.fm integration, where it displays your currently scrobbling tracks?

**Comment by julianschiavo** [comment]
Hey, thanks for using EasyRPC. Can I have:

- a link to lastfm
- what you want support for (is it on web/desktop app?)
- what platform you want support for (macOS/Windows/Linux/All)

Thanks!

**Comment by ghost** [comment]
Sure thing;
https://www.last.fm/
Support is for Last.fm's API i'm guessing
Platform: All

Useful resources:
https://github.com/jonas747/discordlfm
https://github.com/vsTerminus/Discord-NP

**Comment by ghost** [comment]
I'm closing this issue as I've come across another users port
https://github.com/69/fmcord

**Comment by julianschiavo** [comment]
Check Discord :)
