### ISSUE TITLE
Error while trying to install the dependencies

### ISSUE THREAD

**Issue by ElijahPepe** [justdotJS/SimplePresence#21]
## Checklist
- [X] I am on the latest version

- [X] I am on the latest version of dependencies

- [X] I am on the latest version of Discord

- [X] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

- [ ] Feature Request

- [X] Bug Report

## Description
I expected this to download correctly, instead, I got this:

npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/justJS/prism-media.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-03-15T15_36_36_083Z-debug.log
admins-MacBook-Air:SimplePresence admin$ npm i
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout patch-1
npm ERR! error: pathspec 'patch-1' did not match any file(s) known to git

## Specifications
Version is the version of EasyRPC, Platform is Windows/macOS/Linux, and Platform Version is the version of the platform (e.g. 10.13.1 for macOS, or 10 for Windows.).
  - [ ] Version: Newest
  - [ ] Platform: macOS
  - [ ] Platform Version: 10.14.3

**Comment by advaith1** [comment]
Remote prism-media from the package.json

https://github.com/justJS/SimplePresence/issues/20

Please don't create duplicate issues.
