### ISSUE TITLE
delete this issue

### ISSUE THREAD

**Issue by shiypc** [justdotJS/SimplePresence#29]

**Comment by drewbitt** [comment]
I agree that changing the text in a text file isn't ideal when you're already using Electron and can easily write a GUI, but this seems a little heated.

**Comment by drewbitt** [comment]
Nothing you can do about the requirement to have a Discord app to set RPC. All applications need that.

**Comment by pssolanki111** [comment]
tell me you don't understand RPC without telling me you don't understand RPC.
