### ISSUE TITLE
Add Indicators for Song title and Artist Name

### ISSUE THREAD

**Issue by TobiTenno** [justdotJS/SimplePresence#3]
## Checklist
[x] I am on the latest version

[x] I am on the latest version of dependencies

[x] I am on the latest version of Discord

[x] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

[x] Feature Request

[ ] Bug Report

## Description
Add indicators for Song title and Artist Name to their strings. Would love one for time left to keep the  indicators rolling, but it looks like that's managed differently.

(I already have the change ready, it just asked me to make an issue first, so I am.)

Image in implementation: 
![image](https://user-images.githubusercontent.com/7128721/33495667-f6fc831e-d68c-11e7-8971-96f55da951a6.png)

## Specifications
Version is the version of EasyRPC, Platform is Windows/macOS/Linux, and Platform Version is the version of the platform (e.g. 10.13.1 for macOS, or 10 for Windows.).
  - Version: 2.0.4
  - Platform: Windows
  - Platform Version: 10

**Comment by julianschiavo** [comment]
No, I don't want this.
