### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by drewbitt** [justdotJS/SimplePresence#30]
## Checklist
- [ x ] I am on the latest version

- [ x ] I am on the latest version of dependencies

- [ x ] I am on the latest version of Discord

- [ x ] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

[ ] Feature Request

[ x ] Bug Report

## Description
Blank even after writing the text file. Only thing I see is after scrolling down "Upload images". Does not set rich presence in Discord.

![electron_2020-05-08_13-25-31](https://user-images.githubusercontent.com/26885897/81431580-5d1ea000-912f-11ea-9cfd-54309f6efcbc.png)

## Specifications
Version is the version of EasyRPC, Platform is Windows/macOS/Linux, and Platform Version is the version of the platform (e.g. 10.13.1 for macOS, or 10 for Windows.).
  - [ ] Version: EasyRPC? I'm assuming you mean SimplePresence. Latest.
  - [ ] Platform: Windows
  - [ ] Platform Version: 10

`node -v`
v10.15.3
`npm -v`
6.14.1

**Comment by advaith1** [comment]
an electron update broke our translucent background, the text is probably rendered but the same color as the background

**Comment by drewbitt** [comment]
Seems to be the case. Was it transparent before? Because `transparent` is default false and not specified. Setting `transparent` in the browser window to true fixes the error, but seems a little silly because it would only show if there's a dark desktop behind it.

On black
![image](https://user-images.githubusercontent.com/26885897/81457458-2fa01980-9164-11ea-800e-1c041d45cf74.png)

On white
![image](https://user-images.githubusercontent.com/26885897/81457486-4181bc80-9164-11ea-9c15-7e629de13057.png)

Can we change it to a color?

**Comment by drewbitt** [comment]
This is actually because of a breaking change in nodeIntegration https://www.electronjs.org/docs/breaking-changes#planned-breaking-api-changes-50. sending in a PR.
