### ISSUE TITLE
Does not set Discord status

### ISSUE THREAD

**Issue by drewbitt** [justdotJS/SimplePresence#32]
## Checklist
- [x] I am on the latest version

- [x] I am on the latest version of dependencies

- [x] I am on the latest version of Discord

- [x] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

[ ] Feature Request

[x] Bug Report

## Description
Discord rich presence not updated. No errors in console.

Windows 10

**Comment by advaith1** [comment]
in Discord user settings > game activity, can you make sure "show currently playing game as my status" is enabled?

**Comment by drewbitt** [comment]
I swear it wasn't working earlier, but now it is.
