### ISSUE TITLE
Checklist Recommendation - Tasklist instead of pure text

### ISSUE THREAD

**Issue by TobiTenno** [justdotJS/SimplePresence#5]
## Checklist
[x] I am on the latest version

[x] I am on the latest version of dependencies

[x] I am on the latest version of Discord

[x] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

[x] Feature Request

[ ] Bug Report

## Description
Update Issue Template with checkboxes to allow people to complete checklist without editing markdown

## Specifications
Version is the version of EasyRPC, Platform is Windows/macOS/Linux, and Platform Version is the version of the platform (e.g. 10.13.1 for macOS, or 10 for Windows.).
  - Version: 2.0.4
  - Platform: Windows
  - Platform Version: 10

**Comment by Ryonez** [comment]
Creating issue reports are text based, this only pretties up text once it's been phased. It will not let people tick a checkbox, they'll still be editing markdown. If they miss removing the space it looks messed up as well (in original issue md).

Your pr request( #6 ) is messy as well, you missed two boxes, and added 3 where they don't belong.

**Comment by TobiTenno** [comment]
The 2 I didn't add were because they are one or the other, which becomes deceptive in a task list if viewing the issue from the overview. The versions were added so that they could be visually checked as well (adding value from the issue list). Those were a bonus.

**Comment by Ryonez** [comment]
Not sure how the 2 missed would be considered deceptive, it's still one or the other.
The version stuff could be considered deceptive though, because we aren't after a tick, we are after actual versions, which have to be typed in.

**Comment by TobiTenno** [comment]
The 2 "missed" were not missed, they were left out because it's one or the other. 

On a task list, it would still show 1 missing.
In the case of any that were actually completed, with those included, the issue would show as 8/9 on the task list.

**Comment by Ryonez** [comment]
Okay, the one's you left out are still one or the other, *one is meant to be checked/ticked*. 

As to tasklist, what tasklist?

There's a checklist of 4 items, to make sure you've gone through them, and looked for what you needed yourself.

Then there's a multi choice selection, of which you select one

Then there's a description section, where you describe either your issue or feature request

Then there's a section for you to fill in version information. This is most likely only needed for issues. Say that I'm doing a feature request. I could leave this incomplete safely, and then this tasklist is 5/9 complete.

There's no need to make it a massive tasklist, just full in the required information.

Please don't misunderstand, I don't think you're idea is horrible, nor an I trying to attack it. It just doesn't seem feasible here to me.

**Comment by TobiTenno** [comment]
Here is the example from another repo.

![image](https://user-images.githubusercontent.com/7128721/33496561-4dd45a6a-d690-11e7-8ebb-5f1c36feea9a.png)

It's an outside view for stakeholders to get a quick view to see if things are progressing or done yet or not. Those all that have 1 of 2 are formatted like the ones I left out, which are make it confusing as to what they mean.

Here's an example of where we used them as I'm intending them to be used here:
![image](https://user-images.githubusercontent.com/7128721/33496646-99aaabd8-d690-11e7-8fd8-959c036aedfa.png)

In this example, they actually show a progression. The one with 90 things to do is a massive project, and when something gets done, it gets checked off of there.

**Comment by TobiTenno** [comment]
It's an outside view for stakeholders to get a quick view to see if things are progressing or done yet or not. Those all that have 1 of 2 are formatted like the ones I left out, which are make it confusing as to what they mean.

Here's an example of where we used them as I'm intending them to be used here:
![image](https://user-images.githubusercontent.com/7128721/33496646-99aaabd8-d690-11e7-8fd8-959c036aedfa.png)

**Comment by Ryonez** [comment]
0.0

I admit, that looks very pretty, didn't know this was a thing. Hmm, maybe only the first 4 should be down then? Those are required. The feature and issue choice makes sense to leave now, though I still believe that versions aren't required. Those wouldn't need to be filled if it's a feature request after all.

**Comment by TobiTenno** [comment]
I'm mostly referring to a situation where it's an issue, and in this case now, informing you about what you can add to make management of tasks a bit easier this way. If you want them off of the versions, I'll remove them.

**Comment by Ryonez** [comment]
Mhm, thank you. Right now, I don't provide support for the repo, Dot manages that. For now I was pointing out my thoughts on it. 

I'm sure he'll let you know what he thinks once he's back on. Thank you for your time, and for teaching me something!

**Comment by TobiTenno** [comment]
👍 happy to help

**Comment by julianschiavo** [comment]
Accepted.

**Comment by TobiTenno** [comment]
@Ryonez yup, let me know what he thought, and didn't give it a second thought.
