### ISSUE TITLE
Timestamp check on Google Play Music is 100x more than the actual time left

### ISSUE THREAD

**Issue by possiblyanowl** [justdotJS/SimplePresence#7]
## Checklist
- [x] I am on the latest version

- [x] I am on the latest version of dependencies

- [x] I am on the latest version of Discord

- [x] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

[ ] Feature Request

[x] Bug Report

## Description
Replace this text with a description of the bug or feature request. If this is a bug report, include what you expected to happen and what actually happened.
I was noticing that even after enable timestamps, with the "start" config, that it wasn't showing them in rich presence. The app reported a ridiculous number on each song, often in the thousands of minutes. I checked the json file created by GPMDP in ~/.config, and found that it was reporting in ms, and the client was clearly dividing by 60 then reporting it as minutes. I attached a screenshot with more info.

## Specifications
Version is the version of EasyRPC, Platform is Windows/macOS/Linux, and Platform Version is the version of the platform (e.g. 10.13.1 for macOS, or 10 for Windows.).
  - [x] Version: discord-rpc@3.0.0-beta.4 
  - [x] Platform: Arch Linux 
  - [x] Platform Version: N/A

![bug](https://user-images.githubusercontent.com/14366629/33523465-64190718-d7c5-11e7-9777-72da7ad7cbf9.png)

**Comment by possiblyanowl** [comment]
I realize now that I made in error in the calculator screenshot, but if you were to type "265000" as I should have, and not "26500", my theory holds true :)

**Comment by julianschiavo** [comment]
Hey, please ask on the Discord for support, thanks! 
https://discord.gg/MpnbrX7
